<?php

namespace VideoPlayerBundle\Repository;

/**
 * MainVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
