<?php

namespace VideoPlayerBundle\Repository;

/**
 * PlayListYouTubeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayListYouTubeRepository extends \Doctrine\ORM\EntityRepository
{
}
