<?php

namespace VideoPlayerBundle\Repository;

/**
 * YouTubeAnalyticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YouTubeAnalyticsRepository extends \Doctrine\ORM\EntityRepository
{
}
