<?php

namespace VideoPlayerBundle\Repository;

/**
 * YouTubeInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YouTubeInfosRepository extends \Doctrine\ORM\EntityRepository
{
}
