<?php

namespace AppBundle\Repository;

/**
 * FootballAPIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FootballAPIRepository extends \Doctrine\ORM\EntityRepository
{
}
