<?php

namespace AppBundle\Repository;

/**
 * GcmUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GcmUserRepository extends \Doctrine\ORM\EntityRepository
{
}
