<?php

namespace FileManagerBundle\Repository;

/**
 * DownloadFileCounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadFileCounterRepository extends \Doctrine\ORM\EntityRepository
{
}
