<?php

namespace AppBundle\Controller\Main;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MainController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Main\MainController();
        return $instance;
    }
}
