<?php

namespace AppBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ExempleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\ExempleController();
        return $instance;
    }
}
