<?php

namespace FileManagerBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ManagerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \FileManagerBundle\Controller\ManagerController();
        return $instance;
    }
}
