<?php

namespace Symfony\Cmf\Bundle\SeoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SitemapController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Symfony\Cmf\Bundle\SeoBundle\Controller\SitemapController();
        return $instance;
    }
}
